// Copyright (C) 2008-2009 Harm Boschloo

#ifndef COCA_UTILS_FUNCTION_TEST_H_INCLUDED
#define COCA_UTILS_FUNCTION_TEST_H_INCLUDED

void testFunctions();

#endif // COCA_UTILS_FUNCTION_TEST_H_INCLUDED

