#ifndef COCA_VERSION_H_INCLUDED
#define COCA_VERSION_H_INCLUDED

#include "utils/Configuration.h"
#include "utils/Version.h"
#include "utils/preprocessor.h"

// The coca library version
#define COCA_VERSION_MAJOR 0
#define COCA_VERSION_MINOR 0
#define COCA_VERSION_REVISION 0
#define COCA_VERSION_STATUS "alpha"

#define COCA_VERSION_NAME COCA_TO_STRING( COCA_VERSION_MAJOR ) "." COCA_TO_STRING( COCA_VERSION_MINOR ) \
    "." COCA_TO_STRING( COCA_VERSION_REVISION ) " " COCA_VERSION_STATUS

#define COCA_VERSION COCA_VERSION_MAJOR, COCA_VERSION_MINOR, COCA_VERSION_REVISION, COCA_VERSION_STATUS

#endif //COCA_VERSION_H_INCLUDED
