// Copyright (C) 2007-2008 Harm Boschloo

#ifndef E_COCA_DOCUMENT_EVENT_TYPE_H_INCLUDED
#define E_COCA_DOCUMENT_EVENT_TYPE_H_INCLUDED

#include <coca/EEventType.h>

enum ECocaDocumentEventType
{
    E_DOCUMENT_MODIFIED_CHANGED_EVENT = coca::E_NUMBER_OF_EVENT_TYPES,
    E_SYSTEM_CHANGED_EVENT,
    E_ATTRIBUTE_VALUE_CHANGED_EVENT
};

#endif // E_COCA_DOCUMENT_EVENT_TYPE_H_INCLUDED
